#hive-3.1.1和hadoop-2.9.0中的jar包冲突，移除hive的相应包
rm -f /opt/hive/apache-hive-3.1.1-bin/lib/log4j-slf4j-impl-2.10.0.jar

#添加mysql驱动到hive的lib下
cp /root/mysql-connector-java-8.0.16.jar /opt/hive/apache-hive-3.1.1-bin/lib

#主要配置数据库参数
echo '<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
<configuration>
    <property>
        <name>javax.jdo.option.ConnectionURL</name>
        <value>jdbc:mysql://47.107.140.154:3306/hadoophive?allowMultiQueries=true&amp;useSSL=false&amp;verifyServerCertificate=false</value>
    </property>
    <property>
        <name>javax.jdo.option.ConnectionDriverName</name>
        <value>com.mysql.cj.jdbc.Driver</value>
    </property>
    <property>
        <name>javax.jdo.option.ConnectionUserName</name>
        <value>cshare</value>
    </property>
    <property>
        <name>javax.jdo.option.ConnectionPassword</name>
        <value>aBc123456.</value>
    </property>
    <property>
        <name>datanucleus.readOnlyDatastore</name>
        <value>false</value>
    </property>
    <property>
        <name>datanucleus.fixedDatastore</name>
        <value>false</value>
    </property>
    <property>
        <name>datanucleus.autoCreateSchema</name>
        <value>true</value>
    </property>
    <property>
        <name>datanucleus.autoCreateTables</name>
        <value>true</value>
    </property>
    <property>
        <name>datanucleus.autoCreateColumns</name>
        <value>true</value>
    </property>
    <property>
        <name>hive.support.concurrency</name>
        <value>true</value>
    </property>
    <property>
        <name>hive.zookeeper.quorum</name>
        <value>worker3:2181,worker4:2181,worker5:2181</value>
    </property>
    <property>
        <name>hbase.zookeeper.quorum</name>
        <value>worker3:2181,worker4:2181,worker5:2181</value>
    </property>
    <property>
        <name>hive.server2.thrift.port</name>
        <value>10000</value>
    </property>
    <property>
        <name>hive.server2.thrift.bind.host</name>
        <value>worker3</value>
    </property>
    <property>
        <name>hive.server2.transport.mode</name>
        <value>http</value>
    </property>
    <property>
        <name>hive.server2.webui.host</name>
        <value>worker3</value>
    </property>
    <property>
        <name>hive.server2.webui.port</name>
        <value>10002</value>
    </property>
    <property>
        <name>hive.server2.authentication</name>
        <value>NOSASL</value>
    </property>
    <property>
        <name>hive.metastore.schema.verification</name>
        <value>FALSE</value>
    </property>
    <property>
        <name>hive.server2.enable.doAs</name>
        <value>FALSE</value>
    </property>
</configuration>
' >/opt/hive/apache-hive-3.1.1-bin/conf/hive-site.xml